# Generated by Django 2.2 on 2020-10-16 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0006_auto_20201015_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='gig_details',
            new_name='details',
        ),
    ]
